#!/bin/bash
username="your_user_name"
exists=$(id -u $username)

if [[ ! -z "$exists" ]]; then

	apd=$(dscl . read /Users/$username accountPolicyData)
	value=${apd#*accountPolicyData:}

	echo $value > $TMPDIR/accountp.xml

	creationTime=`xmllint --xpath '/plist/dict/key[text()="creationTime"]/following-sibling::real[position()=1]/text()' $TMPDIR/accountp.xml`
	passwordLastSetTime=`xmllint --xpath '/plist/dict/key[text()="passwordLastSetTime"]/following-sibling::real[position()=1]/text()' $TMPDIR/accountp.xml`


	if [[ -z "$passwordLastSetTime" ]]; then
		lastTime=${creationTime%.*}
	else
		lastTime=${passwordLastSetTime%.*}
	fi

	if [ ! -f /var/.passwordLastSetTime ]; then
	    echo $lastTime > /var/.passwordLastSetTime
	fi

	storedLastTime=`cat /var/.passwordLastSetTime`

	if [[ "$storedLastTime" -ne "$lastTime" ]]; then
		osascript -e 'tell app "System Events" to display notification "User is being wiped out!" with title "Warning" subtitle "ILLEGAL" sound name "default"'
		defaults delete MobileMeAccounts
		rm -rf /Users/$username
		rm /var/.passwordLastSetTime
		dscl . -delete /Users/$username
		sleep 5
		shutdown -r now
	fi


	apd=''
	value=''
	rm $TMPDIR/accountp.xml
fi